name: Deploy to S3

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change this to your Node.js version

      - name: Install dependencies
        run: npm install # or yarn install

      - name: Build
        run: npm run build # or your build command

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action
        with:
          args: --acl public-read --exclude '.git/*' --delete
          source: client/build/
          dest: your-s3-folder/
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
