name: Upload to S3 workflow

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          export AWS_ACCESS_KEY_ID=$YOUR_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$YOUR_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1 # Replace with your desired AWS region
          aws s3 sync ./client s3://githubactions--s3/

      
